name: Documentation Build Test

# Controls when the action will run
on:

  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

  # Trigger the workflow on all pull requests
  pull_request:

  # Allow workflow to be dispatched on demand
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      if: ${{ !env.ACT }}  # only if not running in `act` environment

    - name: Install system requirements
      run: >
        sudo apt-get -y update
        && sudo apt-get -y install pandoc

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache Python dependencies
      uses: actions/cache@v2
      if: ${{ !env.ACT }}  # only if not running in `act` environment
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install Python dependencies
      run: python -m pip install -r docs/requirements.txt

    # Run the build command, as per: https://docs.readthedocs.io/en/stable/builds.html
    #
    #   > When we build your Sphinx documentation, we run `sphinx-build -b <format> . _build/<format>`
    #
    # Additional flags "-W --keep-going" are added by `sphinx.fail_on_warning` configuration option, as per:
    #   https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning
    - name: Build the documentation
      run: >
        cd docs
        && rm -rf _build
        && sphinx-build -b html . _build/html -W --keep-going
        && test -f _build/html/index.html
